const { pageManager } = require('../pages/pageManager.js');
const { test, expect } = require('@playwright/test');

test('Navigate to PIM Add Employee',async({page})=>{

    const _pageManager = new pageManager(page);
    const _loginpage = _pageManager.loginPage();
    await _loginpage.gotoLoginPage();//Navigating to URL
    await _loginpage.login('Admin','admin123');//Loggin in with valid username and pasword

    const _pimpage = _pageManager.pimPage();//Creating object for Calling PIM Page class
    const topBarMenus = await _pimpage.navigateToPIMPage();//Clikcing on PIM Menu
    await expect(page.url()).toContain("viewEmployeeList"); //Assert URL
    await expect(topBarMenus).toContain('Add Employee'); // Asert Page to have Add Employee menu
    
    await _pimpage.navigateToAddEmployeePage();//Click on Add Employee button
    await expect(page.url()).toContain("/pim/addEmployee");
    await expect(await _pimpage.formCard).toBeVisible();
});

test('Fill Employee Form', async ({page})=>{
    const _pageManager = new pageManager(page);
    const _loginpage = _pageManager.loginPage();

    //Login
    await _loginpage.gotoLoginPage();//Navigating to URL
    await _loginpage.login('Admin','admin123');//Loggin in with valid username and pasword
    //Navigate to Add Employee
    const _pimpage = _pageManager.pimPage();//Creating object for Calling PIM Page class
    const topBarMenus = await _pimpage.navigateToPIMPage();//Clikcing on PIM Menu
    await _pimpage.navigateToAddEmployeePage();//Click on Add Employee button
    //Fill Form
    await _pimpage.fillForm("Rajnish"," ","Kumar");
    await expect(_pimpage.employeeIdInput).not.toBeEmpty();//Assert that Employee ID is not empty and hence autogenerated
    await expect(_pimpage.employeeIdInput).toBeEditable();//Asserts that Employee Id can be overriden

});

test('Upload Profile Photo', async({page})=>{
    const _pageManager = new pageManager(page);
    const _loginpage = _pageManager.loginPage();

    //Login
    await _loginpage.gotoLoginPage();//Navigating to URL
    await _loginpage.login('Admin','admin123');//Loggin in with valid username and pasword
    //Navigate to Add Employee
    const _pimpage = _pageManager.pimPage();//Creating object for Calling PIM Page class
    const topBarMenus = await _pimpage.navigateToPIMPage();//Clikcing on PIM Menu
    await _pimpage.navigateToAddEmployeePage();//Click on Add Employee button
    //Fill Form
    await _pimpage.fillForm("Rajnish"," ","Kumar");
    await expect(_pimpage.employeeIdInput).not.toBeEmpty();//Assert that Employee ID is not empty and hence autogenerated
    //Upload Photo
    await _pimpage.uploadPhoto();
    await expect(await _pimpage.photoPreview).toHaveAttribute('src',/image\/jpeg/);
});

test('Save and Validate', async ({page})=>{

    const _pageManager = new pageManager(page);
    const _loginpage = _pageManager.loginPage();

    //Login
    await _loginpage.gotoLoginPage();//Navigating to URL
    await _loginpage.login('Admin','admin123');//Loggin in with valid username and pasword
    //Navigate to Add Employee
    const _pimpage = _pageManager.pimPage();//Creating object for Calling PIM Page class
    const topBarMenus = await _pimpage.navigateToPIMPage();//Clikcing on PIM Menu
    await _pimpage.navigateToAddEmployeePage();//Click on Add Employee button
    //Fill Form
    await _pimpage.fillForm("Rajnish","","Kumar");
    await expect(_pimpage.employeeIdInput).not.toBeEmpty();//Assert that Employee ID is not empty and hence autogenerated
    //Save Employee and validate succcess Message
    const message = await _pimpage.saveEmployee();//Click on Save button
    await expect(parseInt(_pimpage.employeeId)).toBeGreaterThan(0);
    await expect(message).toContain('Successfully Saved');
    //Search the employee by ID
    //const id = await _pimpage.searchEmployee();
    //await expect(parseInt(id)).toBe(parseInt(_pimpage.employeeId));
});

