const { test, expect } = require('@playwright/test');
const { pageManager } = require('../pages/pageManager');

test('Search the Employee', async({page})=>{

    const _pageManager = new pageManager(page);
    const _loginpage = _pageManager.loginPage();
    
    //Login
    await _loginpage.gotoLoginPage();//Navigating to URL
    await _loginpage.login('Admin','admin123');//Loggin in with valid username and pasword

    //Navigate to Add Employee
    const _pimpage = _pageManager.pimPage();//Creating object for Calling PIM Page class
    const topBarMenus = await _pimpage.navigateToPIMPage();//Clikcing on PIM Menu
    await _pimpage.navigateToAddEmployeePage();//Click on Add Employee button

    //Fill Form
    await _pimpage.fillForm("Rajnish","","Kumar");
    await expect(_pimpage.employeeIdInput).not.toBeEmpty();//Assert that Employee ID is not empty and hence autogenerated

    //Save Employee and validate succcess Message
    const message = await _pimpage.saveEmployee();//Click on Save button
    await expect(parseInt(_pimpage.employeeId)).toBeGreaterThan(0);
    await expect(message).toContain('Successfully Saved');

    //Search the employee by ID
    const id = await _pimpage.searchEmployee();
    await expect(parseInt(id)).toBe(parseInt(_pimpage.employeeId));
});